### ISSUE TITLE
How about add file filter to only reformat `*.py` files.

### ISSUE THREAD

**Issue by v1c77** [cryeo/yapf-plugin#2]
I tested either with the config `reformat on save` or use the shortcut to reformat current file.
It can not recognize out a python file and always sys out a error log to pycharm event log about:
```
16:13	YAPF
			File is unformattable
```
Or is there any other way like add some config to `.style.yapf` ? 
Thank you. : )

**Comment by cryeo** [comment]
Hello,

`File is unformattable` occurs in following situations:
- It is unable to get file path.
- File type is not python. (this is determined by IDE) 
- File extension is not ended with `.py`.

There are two ways to reformat code via this plugin:
- Perform action `Reformat code with YAPF`
- Save code with setting `Format on save`

The latter has a limitation that target file should belong to current project. 

I tried to regenerate situation in PyCharm CE 2018.2 but I could not. 
Could you tell me information in detail? :)

**Comment by v1c77** [comment]
sorry for my incoherent words.
I just mean that this plugin always try to reformat all the files in my project but I only want it focus on 
 those python files. 

On my  opinion, maybe you can change the  log `File is unformattable` from level `error` to `warn` or just *info*,  please just not raise the notice window.

Or,  you can change the strategy that only in python file the plugin will be activated.

**Comment by cryeo** [comment]
Thanks, I'll modify it on next version :)

**Comment by cryeo** [comment]
Fixed on v0.2
